local mod = get_mod("game-stats")

mod.interesting_numbers = {
	"chaos_troll_killed_without_bile_damage",
	"perfect_bile_troll",
	"kill_skaven_storm_vermin_warlord_difficulty_rank",
	"warpfire_kill_before_shooting",
	"pack_master_dodged_attack",
	"catacombs_added_souls",
	"chaos_spawn_killed_without_having_grabbed",
	"total_collected_tomes",
	"stormfiend_killed_on_controller",
	"globadier_kill_before_throwing",
	"perfect_rat_ogre",
	"rat_ogre_killed_without_dealing_damage",
	"exalted_champion_charge_chaos_warrior",
	"globadier_kill_during_suicide",
	"completed_heroic_deeds",
	"vortex_sorcerer_killed_while_ally_in_vortex",
	"corruptor_dodged_attack",
	"ratling_gunner_killed_by_melee",
	"dynamic_objects_destroyed",
	"kill_chaos_exalted_sorcerer_difficulty_rank",
	"gutter_runner_push_on_pounce",
	"pack_master_rescue_hoisted_ally",
	"warpfire_enemies_killed_by_warpfire",
	"chaos_spawn_killed_while_grabbing",
	"ratling_gunner_blocked_shot",
	"chaos_troll_killed_without_regen",
	"globadier_enemies_killed_by_poison",
	"corruptor_killed_at_teleport_time",
	"ratling_gunner_killed_while_shooting",
	"kill_chaos_exalted_champion_difficulty_rank",
	"vortex_sorcerer_killed_while_summoning",
	"perfect_chaos_spawn",
	"warpfire_kill_on_power_cell",
	"kill_skaven_grey_seer_difficulty_rank",
	"total_collected_grimoires",
	"corruptor_killed_while_grabbing",
	"gutter_runner_killed_on_pounce",
	"stormfiend_killed_without_burn_damage",
	"last_played_level_id",
	"vortex_sorcerer_killed_by_melee",
	"crafted_items",
	"times_friend_healed",
	"pack_master_kill_abducting_ally",
	"salvaged_items",
	"gutter_runner_push_on_target_pounced",
	"perfect_storm_fiend",
}

mod.interesting_tables = {
	"played_levels_quickplay",
	"completed_levels",
	"played_difficulty",
}
